### PR TITLE
More accurate duration

### PR DESCRIPTION
**Pull request by KoltesDigital**
I found useful to have a more accurate duration. This change keeps the duration as a number in milliseconds.

### CODE REVIEW

**Comment by vvo** [comment]
Hi, thanks a lot!

So what does the duration looks like now? Can you show me an example?

Where do you use this module?

**Comment by KoltesDigital** [comment]
It's just `duration: 3.65378` instead of `duration: 3`. Not that the precision below 1ms is important to me (maybe for a big site it is?), but I trust `process.hrtime()` more than `Date.now()` for comparing time intervals. Besides, it's exactly the example given [in the doc of `process.hrtime`](https://nodejs.org/api/process.html#process_process_hrtime). It would be interesting to test if the two functions returns significantly different values above 1ms.

I made a somewhat similar middleware at work, but at home I won't duplicate it on every project, so it's best to improve your implementation :)

**Comment by vvo** [comment]
Thanks for comments, Let's merge!

**Comment by vvo** [comment]
published as 1.2.0

**Pull request merged**
