### PR TITLE
Adding includeRequestInEnd property to include request in 'end lesson' l...

### PR DESCRIPTION
**Pull request by loudwinston**
Added an option to include the request in the "end request" log message.  This makes it easier to see details of the request that generated the response (url, POST parameters, etc)

### CODE REVIEW

**Comment by vvo** [comment]
@loudwinston There's already an id for the request that you can map to the same id for the response if you want to know which request generated a particular response.

**Comment by loudwinston** [comment]
Yes, but doing using the request id means that I have to correlate two separate log entries to find out what request triggered a given response.  This makes it harder for me to quickly look at a log entry in my log aggregator (loggly).  

bunyan-middleware includes the request and response when emitting the 'end request' log.  Do you not see this as a useful feature at all?

**Comment by vvo** [comment]
What I disliked about bunyan-middleware is that it has a lot of options and thus makes it harder to use it.

Most of the time I would use bunyan-request and combine it with a logger aggregator where I will do the mapping. So that I do not put redundancy in logs just because I want to see them linked in the console.

Makes sense?

**Comment by loudwinston** [comment]
Sure, striving for simplicity is a valid goal.  In my case I think we're going to switch to bunyan-middleware since it mets our needs a bit better.  Thanks!

**Pull request closed without merging**
