### PR TITLE
Support for custom serializer

### PR DESCRIPTION
**Pull request by americanbhau**
Provides support for custom serializer.

### CODE REVIEW

**Comment by americanbhau** [comment]
@vvo Support for custom serializer with a test.

**Comment by vvo** [comment]
Awesome, let's go!

**Comment by vvo** [comment]
@aleric323 would you like to be a maintainer of this module? I have very little time nowadays and you seem to be using it for great!

If so, let me know what's your npm username and I will add you

**Comment by americanbhau** [comment]
@vvo Sure, I don't mind. The username is same on npm (aleric323).

**Comment by vvo** [comment]
@aleric323 added! Use pull requests, merge, release you can do all of that, 🙏

**Pull request merged**
